In [2]:
import polars as pl

In [5]:
df = pl.read_csv("../hospital_readmission_dataset.csv")
df.head()

shape: (5, 17)
┌────────────┬──────────────┬────────┬─────┬───┬──────────────┬──────────────┬─────────────┬───────┐
│ patient_id ┆ admission_da ┆ season ┆ age ┆ … ┆ insurance_ty ┆ discharge_di ┆ readmission ┆ label │
│ ---        ┆ te           ┆ ---    ┆ --- ┆   ┆ pe           ┆ sposition    ┆ _risk_score ┆ ---   │
│ str        ┆ ---          ┆ str    ┆ i64 ┆   ┆ ---          ┆ ---          ┆ ---         ┆ i64   │
│            ┆ str          ┆        ┆     ┆   ┆ str          ┆ str          ┆ f64         ┆       │
╞════════════╪══════════════╪════════╪═════╪═══╪══════════════╪══════════════╪═════════════╪═══════╡
│ P00001     ┆ 2022-04-14   ┆ Spring ┆ 66  ┆ … ┆ Medicare     ┆ Home Health  ┆ 0.92        ┆ 1     │
│ P00002     ┆ 2021-09-19   ┆ Fall   ┆ 55  ┆ … ┆ Private      ┆ Home Health  ┆ 0.88        ┆ 1     │
│ P00003     ┆ 2023-04-12   ┆ Spring ┆ 69  ┆ … ┆ Medicare     ┆ Skilled      ┆ 0.97        ┆ 1     │
│            ┆              ┆        ┆     ┆   ┆              ┆ Nursing      ┆             ┆       │
│ P00004     ┆ 2023-08-14   ┆ Summer ┆ 83  ┆ … ┆ Medicare     ┆ Skilled      ┆ 0.97        ┆ 1     │
│            ┆              ┆        ┆     ┆   ┆              ┆ Nursing      ┆             ┆       │
│ P00005     ┆ 2021-11-05   ┆ Fall   ┆ 54  ┆ … ┆ Uninsured    ┆ Home Health  ┆ 0.83        ┆ 1     │
└────────────┴──────────────┴────────┴─────┴───┴──────────────┴──────────────┴─────────────┴───────┘

In [6]:
df.describe()

shape: (9, 18)
┌────────────┬────────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic  ┆ patient_id ┆ admission_ ┆ season ┆ … ┆ insurance ┆ discharge ┆ readmissi ┆ label    │
│ ---        ┆ ---        ┆ date       ┆ ---    ┆   ┆ _type     ┆ _disposit ┆ on_risk_s ┆ ---      │
│ str        ┆ str        ┆ ---        ┆ str    ┆   ┆ ---       ┆ ion       ┆ core      ┆ f64      │
│            ┆            ┆ str        ┆        ┆   ┆ str       ┆ ---       ┆ ---       ┆          │
│            ┆            ┆            ┆        ┆   ┆           ┆ str       ┆ f64       ┆          │
╞════════════╪════════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count      ┆ 8000       ┆ 8000       ┆ 8000   ┆ … ┆ 8000      ┆ 8000      ┆ 8000.0    ┆ 8000.0   │
│ null_count ┆ 0          ┆ 0          ┆ 0      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0      │
│ mean       ┆ null       ┆ null       ┆ null   ┆ … ┆ null      ┆ null      ┆ 0.7769375 ┆ 0.772875 │
│ std        ┆ null       ┆ null       ┆ null   ┆ … ┆ null      ┆ null      ┆ 0.219885  ┆ 0.419    │
│ min        ┆ P00001     ┆ 2021-01-01 ┆ Fall   ┆ … ┆ Medicaid  ┆ Home      ┆ 0.07      ┆ 0.0      │
│ 25%        ┆ null       ┆ null       ┆ null   ┆ … ┆ null      ┆ null      ┆ 0.63      ┆ 1.0      │
│ 50%        ┆ null       ┆ null       ┆ null   ┆ … ┆ null      ┆ null      ┆ 0.86      ┆ 1.0      │
│ 75%        ┆ null       ┆ null       ┆ null   ┆ … ┆ null      ┆ null      ┆ 0.97      ┆ 1.0      │
│ max        ┆ P08000     ┆ 2023-12-31 ┆ Winter ┆ … ┆ Uninsured ┆ Skilled   ┆ 0.97      ┆ 1.0      │
│            ┆            ┆            ┆        ┆   ┆           ┆ Nursing   ┆           ┆          │
└────────────┴────────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴──────────┘