# Import libraries

In [39]:
import polars as pl
from datetime import datetime

# Load dataset

In [40]:
df = pl.read_csv("../hospital_readmission_dataset.csv")
df.head()

shape: (5, 17)
┌────────────┬──────────────┬────────┬─────┬───┬──────────────┬──────────────┬─────────────┬───────┐
│ patient_id ┆ admission_da ┆ season ┆ age ┆ … ┆ insurance_ty ┆ discharge_di ┆ readmission ┆ label │
│ ---        ┆ te           ┆ ---    ┆ --- ┆   ┆ pe           ┆ sposition    ┆ _risk_score ┆ ---   │
│ str        ┆ ---          ┆ str    ┆ i64 ┆   ┆ ---          ┆ ---          ┆ ---         ┆ i64   │
│            ┆ str          ┆        ┆     ┆   ┆ str          ┆ str          ┆ f64         ┆       │
╞════════════╪══════════════╪════════╪═════╪═══╪══════════════╪══════════════╪═════════════╪═══════╡
│ P00001     ┆ 2022-04-14   ┆ Spring ┆ 66  ┆ … ┆ Medicare     ┆ Home Health  ┆ 0.92        ┆ 1     │
│ P00002     ┆ 2021-09-19   ┆ Fall   ┆ 55  ┆ … ┆ Private      ┆ Home Health  ┆ 0.88        ┆ 1     │
│ P00003     ┆ 2023-04-12   ┆ Spring ┆ 69  ┆ … ┆ Medicare     ┆ Skilled      ┆ 0.97        ┆ 1     │
│            ┆              ┆        ┆     ┆   ┆              ┆ Nursing      ┆             ┆       │
│ P00004     ┆ 2023-08-14   ┆ Summer ┆ 83  ┆ … ┆ Medicare     ┆ Skilled      ┆ 0.97        ┆ 1     │
│            ┆              ┆        ┆     ┆   ┆              ┆ Nursing      ┆             ┆       │
│ P00005     ┆ 2021-11-05   ┆ Fall   ┆ 54  ┆ … ┆ Uninsured    ┆ Home Health  ┆ 0.83        ┆ 1     │
└────────────┴──────────────┴────────┴─────┴───┴──────────────┴──────────────┴─────────────┴───────┘

# Drop unneeded columns

In [41]:
df = df.drop("readmission_risk_score")
df = df.drop("patient_id")

In [42]:
df.describe()

shape: (9, 16)
┌────────────┬────────────┬────────┬───────────┬───┬────────────┬───────────┬───────────┬──────────┐
│ statistic  ┆ admission_ ┆ season ┆ age       ┆ … ┆ prev_readm ┆ insurance ┆ discharge ┆ label    │
│ ---        ┆ date       ┆ ---    ┆ ---       ┆   ┆ issions    ┆ _type     ┆ _disposit ┆ ---      │
│ str        ┆ ---        ┆ str    ┆ f64       ┆   ┆ ---        ┆ ---       ┆ ion       ┆ f64      │
│            ┆ str        ┆        ┆           ┆   ┆ f64        ┆ str       ┆ ---       ┆          │
│            ┆            ┆        ┆           ┆   ┆            ┆           ┆ str       ┆          │
╞════════════╪════════════╪════════╪═══════════╪═══╪════════════╪═══════════╪═══════════╪══════════╡
│ count      ┆ 8000       ┆ 8000   ┆ 8000.0    ┆ … ┆ 8000.0     ┆ 8000      ┆ 8000      ┆ 8000.0   │
│ null_count ┆ 0          ┆ 0      ┆ 0.0       ┆ … ┆ 0.0        ┆ 0         ┆ 0         ┆ 0.0      │
│ mean       ┆ null       ┆ null   ┆ 57.411625 ┆ … ┆ 1.5725     ┆ null      ┆ null      ┆ 0.772875 │
│ std        ┆ null       ┆ null   ┆ 16.724388 ┆ … ┆ 0.89196    ┆ null      ┆ null      ┆ 0.419    │
│ min        ┆ 2021-01-01 ┆ Fall   ┆ 18.0      ┆ … ┆ 0.0        ┆ Medicaid  ┆ Home      ┆ 0.0      │
│ 25%        ┆ null       ┆ null   ┆ 46.0      ┆ … ┆ 1.0        ┆ null      ┆ null      ┆ 1.0      │
│ 50%        ┆ null       ┆ null   ┆ 57.0      ┆ … ┆ 1.0        ┆ null      ┆ null      ┆ 1.0      │
│ 75%        ┆ null       ┆ null   ┆ 69.0      ┆ … ┆ 2.0        ┆ null      ┆ null      ┆ 1.0      │
│ max        ┆ 2023-12-31 ┆ Winter ┆ 95.0      ┆ … ┆ 5.0        ┆ Uninsured ┆ Skilled   ┆ 1.0      │
│            ┆            ┆        ┆           ┆   ┆            ┆           ┆ Nursing   ┆          │
└────────────┴────────────┴────────┴───────────┴───┴────────────┴───────────┴───────────┴──────────┘

# Convert date to week day

In [43]:
df = df.with_columns(
    pl.col("admission_date").str.to_date().dt.to_string("%A").alias("admission_weekday")
).drop("admission_date")

In [44]:
df['admission_weekday'].head()

shape: (10,)
Series: 'admission_weekday' [str]
[
	"Thursday"
	"Sunday"
	"Wednesday"
	"Monday"
	"Friday"
	"Thursday"
	"Tuesday"
	"Saturday"
	"Monday"
	"Saturday"
]

# One-Hot encoding for categorical variables

In [45]:
df.head()

shape: (5, 15)
┌────────┬─────┬────────┬────────┬───┬────────────────┬──────────────────┬───────┬─────────────────┐
│ season ┆ age ┆ gender ┆ region ┆ … ┆ insurance_type ┆ discharge_dispos ┆ label ┆ admission_weekd │
│ ---    ┆ --- ┆ ---    ┆ ---    ┆   ┆ ---            ┆ ition            ┆ ---   ┆ ay              │
│ str    ┆ i64 ┆ str    ┆ str    ┆   ┆ str            ┆ ---              ┆ i64   ┆ ---             │
│        ┆     ┆        ┆        ┆   ┆                ┆ str              ┆       ┆ str             │
╞════════╪═════╪════════╪════════╪═══╪════════════════╪══════════════════╪═══════╪═════════════════╡
│ Spring ┆ 66  ┆ Male   ┆ South  ┆ … ┆ Medicare       ┆ Home Health      ┆ 1     ┆ Thursday        │
│ Fall   ┆ 55  ┆ Male   ┆ South  ┆ … ┆ Private        ┆ Home Health      ┆ 1     ┆ Sunday          │
│ Spring ┆ 69  ┆ Female ┆ West   ┆ … ┆ Medicare       ┆ Skilled Nursing  ┆ 1     ┆ Wednesday       │
│ Summer ┆ 83  ┆ Male   ┆ South  ┆ … ┆ Medicare       ┆ Skilled Nursing  ┆ 1     ┆ Monday          │
│ Fall   ┆ 54  ┆ Female ┆ North  ┆ … ┆ Uninsured      ┆ Home Health      ┆ 1     ┆ Friday          │
└────────┴─────┴────────┴────────┴───┴────────────────┴──────────────────┴───────┴─────────────────┘

In [46]:
# One-Hot Encoding

In [47]:
df.to_dummies(["season", "gender", "region", "primary_diagnosis", "treatment_type", "insurance_type", "discharge_disposition", "admission_weekday"], drop_first=True)

shape: (8_000, 40)
┌────────────┬────────────┬────────────┬─────┬───┬────────────┬────────────┬───────────┬───────────┐
│ season_Fal ┆ season_Sum ┆ season_Win ┆ age ┆ … ┆ admission_ ┆ admission_ ┆ admission ┆ admission │
│ l          ┆ mer        ┆ ter        ┆ --- ┆   ┆ weekday_Sa ┆ weekday_Su ┆ _weekday_ ┆ _weekday_ │
│ ---        ┆ ---        ┆ ---        ┆ i64 ┆   ┆ turday     ┆ nday       ┆ Tuesday   ┆ Wednesday │
│ u8         ┆ u8         ┆ u8         ┆     ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│            ┆            ┆            ┆     ┆   ┆ u8         ┆ u8         ┆ u8        ┆ u8        │
╞════════════╪════════════╪════════════╪═════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 0          ┆ 0          ┆ 0          ┆ 66  ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ 0         │
│ 1          ┆ 0          ┆ 0          ┆ 55  ┆ … ┆ 0          ┆ 1          ┆ 0         ┆ 0         │
│ 0          ┆ 0          ┆ 0          ┆ 69  ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ 1         │
│ 0          ┆ 1          ┆ 0          ┆ 83  ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ 0         │
│ 1          ┆ 0          ┆ 0          ┆ 54  ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ 0         │
│ …          ┆ …          ┆ …          ┆ …   ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 0          ┆ 0          ┆ 1          ┆ 95  ┆ … ┆ 0          ┆ 0          ┆ 1         ┆ 0         │
│ 0          ┆ 0          ┆ 0          ┆ 63  ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ 0         │
│ 0          ┆ 1          ┆ 0          ┆ 43  ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ 0         │
│ 0          ┆ 0          ┆ 0          ┆ 86  ┆ … ┆ 0          ┆ 0          ┆ 1         ┆ 0         │
│ 0          ┆ 1          ┆ 0          ┆ 93  ┆ … ┆ 1          ┆ 0          ┆ 0         ┆ 0         │
└────────────┴────────────┴────────────┴─────┴───┴────────────┴────────────┴───────────┴───────────┘

In [52]:
df.write_parquet("01_preprocessing/data.parquet")

FileNotFoundError: No such file or directory (os error 2): 01_preprocessing/data.parquet